CHANGELOG

I added a change log file containing the changes up to August 24th.
If you merge this, please make sure to update it accordingly.
When new features/bugfixes/changes are made to opensheetmusicdisplay, this file should be updated as well.
The structure is taken from http://keepachangelog.com/. Every release has an _Added_, _Changed_ and _Bugs_ section.
Changes are top-down, so latest go to the top. That's not too important however. It would be nice to include hashes for commits or references to PRs, but I didn't do that for the past releases fo time reasons.

Add change log

---

demo/demo.js
demo/index.html
package.json
src/OSMD/OSMD.ts
typings.json

See #21 
Added [loglevel](https://www.npmjs.com/package/loglevel)
Easy to use:
```javascript
log.trace(msg);
log.debug(msg);
log.info(msg);
log.warn(msg);
log.error(msg);
```
You can get different loggers, set log levels application-wide or per logger, etc.
Will resolve both #21 and #9.

Added loglevel as logging framework

---

package.json
src/MusicalScore/Graphical/VexFlow/VexFlowConverter.ts
src/MusicalScore/Graphical/VexFlow/VexFlowMeasure.ts
test/MusicalScore/Graphical/VexFlow/VexFlowConverter_Clef_Test.ts

… Lines are now respected during conversion of MusicXML/OSMD Clefs to VexFlow clef rendering instructions.
See #110

feat(clef): Improved conversion of ClefInstructions to VexFlow clefs

---

Gruntfile.js
package.json

So I added a basic webpack setup for grunt. Here some stats:
| Tool  | Size|
| ------------- | ------------- |
|Browserify|2.4MB|
|Browserify + Uglify | 768kB |
|Webpack|2.4MB|
|Webpack + UglifyPlugin|1.1MB|
|Webpack + UglifyPlugin + Uglify|754kB|
So maybe there are some options that I am missing but it doesn't look like a great leap sizewise. Anyways webpack offers heaps of plugins as you mention in issue #103 which might be benefitial.

Added webpack build for grunt, issue #103 #121

---

demo/demo.js
demo/index.html
external/vexflow/vexflow.d.ts
src/MusicalScore/Graphical/VexFlow/CanvasVexFlowBackend.ts
src/MusicalScore/Graphical/VexFlow/SvgVexFlowBackend.ts
src/MusicalScore/Graphical/VexFlow/VexFlowBackend.ts
src/MusicalScore/Graphical/VexFlow/VexFlowConverter.ts
src/MusicalScore/Graphical/VexFlow/VexFlowMeasure.ts
src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetDrawer.ts
src/MusicalScore/Graphical/VexFlow/VexFlowTextMeasurer.ts
src/OSMD/OSMD.ts
test/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetDrawer_Test.ts

In order to solve the "blurriness" on Retina displays, I've added an option to render the music drawer by using the SVG backend from VexFlow.
I've also encapsulated logic related to the backend (ie: fillRect, translate, etc) to a separate class, so different strategies for custom rendering can be implemented, for SVG and Canvas. To test this, go to the demo page and select the SVG backend: http://jportela-osmd.netlify.com/
Currently, there are a few outstanding issues, which I think make sense to solve before merging this:
* Text Styles are not rendered
* Re-rendering a SVG-backend score will duplicate the "rendering artifacts" (try using the demo page with SVG, and resize it)
* I haven't added any documentation explaining that the new backend could be used (once it's stable, I can write …

Adds SVG Rendering option

---

package.json

Hi,
When installing opensheetmusicdisplay on a new project, if we don't have rimraf installed, installation fails. I know my solution is UNIX only but maybe we could just keep the typings folder?
Thanks.
-- 
Vincent

Remove global dependency on rimraf 

---

src/MusicalScore/Graphical/BoundingBox.ts
src/MusicalScore/Graphical/VexFlow/VexFlowStaffEntry.ts
src/MusicalScore/VoiceData/SourceMeasure.ts
src/OpenSheetMusicDisplay/OpenSheetMusicDisplay.ts

Changed all missing debug and error outputs so that they print using the `loglevel `framework.
- How can we put OSMD components into logical groups in terms of logging? I can imagine something, where it would be possible to mute all errors and warnings coming from the MusicXML reading parts but displaying the ones that result from rendering etc.
- Do we really need class names etc in the logging statement as @bneumann pointed out? loglevel does not alter the source of the call so with sourcemaps activated, you can easily find the origin of the log statement.

Migration to loglevel for all logging statements

---

src/MusicalScore/Graphical/MusicSheetCalculator.ts

Shortened lyrics y-offset below the staff.
Now lyrics much better belong to the corresponding staff visually,
as with physical sheet music editions.
(also, some typo fixes)
I believe the lyrics Y offset was unnecessarily extended by EngravingRules.StaffHeight, because it's already set to Math.max of StaffHeight and the bounding box. no need to add StaffHeight to the bounding box.
(We shouldn't be too worried about a collision right at the bounding box. Most letters won't reach it, and most notes will not reach it either. Even if we're worried, we should only add a very small offset, maybe 0.1, not the 3.0 of StaffHeight)
Comparison screenshots below, first current state before fix:
(of course, the blue bounding box lines only show with debug information/bottomlines)
The third and fourth …

fix(MusicSheetCalculator.ts): shorten lyrics y offset

---

src/MusicalScore/Graphical/VexFlow/VexFlowConverter.ts
src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetCalculator.ts
src/MusicalScore/ScoreIO/InstrumentReader.ts
test/MusicalScore/ScoreIO/Key_Test.ts

2 fixes:
fix(KeySignatureParse): key signature displayed correctly when mode not set in XML
fix(TimeSignatures): common time and alla breve display correctly
Previously, common time(C) was displayed as 4/4 and alla breve(C|) as 2/2,
and the D major signature in An die Musik was read as no key signature because mode attribute was missing:

Fix key signature without mode, common/alla breve time

---

demo/demo.css
demo/index.html
demo/index.js

* Before the fix, long sample names were cut off in the sample drop-down list:
* Now, the box can fit all current sample names:
* Also, the comma in "Beethoven, L.v." would have been cut off before the fix, because the box height is too low, so it looks like a dot.
* I also reversed the order of first name and last name so last name is first, which is easier to read.
I would also like having no first name at all (e.g. for Beethoven), but it can be confusing (Joplin, Levasseur).
* There are some issues when you shrink the browser width too much, but that was also the case before, only at smaller widths.
* I also refactored some variable names which weren't clear (select -> selectSamples)

Fix demo select sample width, reorganize sample list

---

package.json

We finally got a new Vexflow release, and it fixes many layouting bugs:
* Delayed ornament x-shift
* Grace notes x-shift
* NoteSubGroup, In-Measure Clef x-shift
* (Dotted note dot y-shift, in previous master builds)
I used this version extensively, looked at most samples, and didn't notice breaking changes (that i didn't already fix).
(do npm install to use the new version)

Update vexflow to new version 1.2.85 (fixes bugs)

---

demo/index.js

Without the fix right now we get an error in the console when starting the demo, which is a bit annoying:
(see StackTrace at bottom)
This is because in index.js.init(), we call index.js.Resize(...,endCallback), which calls opensheetmusicdisplay.render(), before we loaded a sample.
Of course the demo doesn't have to be perfectly coded, but it's a bit strange to call new Resize() (index.js:194) on a function Resize(), which gets executed immediately, and the error is annoying. (We only recently started showing this error with console.warn() in index.js:133)
In any case, i used a sampleLoaded boolean and this fixes the error on initialization.
<details>
<summary>
StackTrace
</summary>
```
Error: OpenSheetMusicDisplay: Before rendering a music sheet, please load a MusicXML file
at …
```

fix(demo): fix console warning on init

---

demo/index.html
src/MusicalScore/Graphical/EngravingRules.ts
src/MusicalScore/Graphical/MusicSheetCalculator.ts
src/MusicalScore/Graphical/VexFlow/VexFlowConverter.ts
src/MusicalScore/Graphical/VexFlow/VexFlowStaffEntry.ts

Fix #380
* Fix whole rest Bounding Box (for StaffEntry, VoiceEntry, GraphicalNote), fixing Cursor position
* Add GraphicalNotes and VoiceEntries options to show bbox
* Demo: Rename "Show bounding box" options to be more similar to class names
The bbox fix isn't pretty, but that's because the bounding box given by Vexflow is completely wrong.
Test Xml with some rest variations:
[Whole_Rest_Bbox_test.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/2376420/Whole_Rest_Bbox_test.zip)

Fix Whole Rest Bbox/Cursor

---

src/Common/Strings/StringUtil.ts
src/MusicalScore/ScoreIO/MusicSymbolModules/RepetitionCalculator.ts
src/MusicalScore/ScoreIO/MusicSymbolModules/RepetitionInstructionReader.ts

Fixes #370
Our StringUtil.StringContainsSeparatedWord function was implemented as if it used plain strings instead of RegExes with String.search(). The function should work as designed now, with proper RegExes.
Also fixes a crash in RepetitionCalculator when currentMeasure was not set.

Fix RepetitionReader RegExes, RepetitionCalculator crash

---

demo/index.js
karma.conf.js
src/MusicalScore/Graphical/DrawingParameters.ts
src/MusicalScore/Graphical/MusicSheetDrawer.ts
src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetDrawer.ts
src/OpenSheetMusicDisplay/Cursor.ts
src/OpenSheetMusicDisplay/OSMDOptions.ts
src/OpenSheetMusicDisplay/OpenSheetMusicDisplay.ts
test/Common/FileIO/Xml_Test.ts
test/Common/OSMD/OSMD_Test.ts
test/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetDrawer_Test.ts
test/Util/TestUtils.ts
webpack.prod.js

Resolves #288
Adds an interface for options that replaces the individual options parameters in the OpenSheetMusicDisplay() constructor, as @sebastianhaas suggested in #288.
Any changes you and @bneumann want to see?
I added the interface to OpenSheetMusicDisplay.ts and exported it, so i hope people using OSMD with TypeScript can import the interface as well.
But this may not be the best way to go about it, maybe it should go into a new file.
```javascript
export interface IOSMDOptions {
autoBeam?: boolean; // not yet supported. will always autoBeam.
autoResize?: boolean; // default is false
autoStem?: boolean; // not yet supported. will always autoStem
backend?: string; // Backend will be SVG if backend === "svg", otherwise Canvas
disableCursor?: boolean; // will override this part of …
```

feat: options interface for osmd constructor

---

demo/index.js
external/vexflow/vexflow.d.ts
src/MusicalScore/Graphical/VexFlow/VexFlowMeasure.ts
src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetCalculator.ts
src/MusicalScore/Graphical/VexFlow/VexFlowStaffEntry.ts
src/MusicalScore/ScoreIO/MusicSheetReader.ts
src/OpenSheetMusicDisplay/OpenSheetMusicDisplay.ts

Can now render an empty score, Fixes #358 (see top comment there for XML sample)
Adds general improvements to error handling (undefined voices, parsing, calling getBoundingBox() on unformatted StaveNotes).
OSMD now returns an error if the MusicSheet read was undefined. Previously, this would cause random Errors and StackTraces in new GraphicalMusicSheet() (e.g. Staves undefined).
Also changed log.warn to log.info for a measure without voices in VexFlowMusicSheetCalculator.
log.warn produces warnings for the end user.
This still doesn't include XML verification, but one incomplete XML i tried simply gave another empty score, another returned an error "Error: given music sheet was incomplete or could not be loaded", as designed.
Discussion of validation in #358.

Fix error loading empty score, improve error handling

---

demo/index.html
src/MusicalScore/Graphical/AlignmentManager.ts
src/MusicalScore/Graphical/GraphicalContinuousDynamicExpression.ts
src/MusicalScore/Graphical/MusicSheetCalculator.ts
src/MusicalScore/Graphical/StaffLine.ts
src/OpenSheetMusicDisplay/OpenSheetMusicDisplay.ts
test/data/OSMD_function_test_expressions_overlap.musicxml

Spacing between two crescendos is already fixed here:
I couldn't figure out how to fix the spacing between crescendo and e.g. a forte though, like in the Entertainer:
It's strange because it works well in the function test Expressions Overlap.
The problem may be that in the Entertainer, the crescendo ends at the first note of the next bar.
This is a pretty common setup though, also found in Schubert - An die Musik.
I also added an option to [show wedges bounding boxes](https://user-images.githubusercontent.com/33069673/46909121-b57ac500-cf2d-11e8-8300-55704c98f436.png) to the demo.

fix crescendo spacing

---

demo/demo.css
demo/index.html
demo/index.js
src/MusicalScore/Graphical/EngravingRules.ts
src/OpenSheetMusicDisplay/OpenSheetMusicDisplay.ts

osmd: autoResize defaults to true, add clear(), isReadyToRender() methods
osmd: fix autoResize handling: don't attach listeners multiple times, don't set timeouts if autoResize disabled
previously, disabling autoResize at runtime didn't work.
index.html: add clear button, improve re-render button size/layout
index.js (demo): null-check buttons for public demo, remove resize code (handled by osmd)
In the demo, try combinations of clear, re-render and this in the console:
`osmd.setOptions({autoResize: false})` (or true)
closes #403 (null-checks for github.io demo which has less buttons. better solved here)
closes #387 (autoResize code in osmd and index.js isn't inconsistent and duplicate anymore)

set autoResize at runtime, fix autoResize handling, demo null checks

---

src/OpenSheetMusicDisplay/Cursor.ts
test/Common/OSMD/OSMD_Test.ts

Calling `cursor.next()` might throw an error when an instrument is invisible (i.e. `osmd.Sheet.Instruments[0].Visible = false` is set and `osmd.render()` is called):
```
TypeError: Cannot read property 'PositionAndShape' of undefined
at Cursor../src/OpenSheetMusicDisplay/Cursor.ts.Cursor.update:73
```
This happens if all of the voice entries under cursor are hidden. In other words, when the currently visible voices under cursor have no notes, but the hidden ones do.
I solved this problem by modifying the `Cursor#update()` method to use `iterator.CurrentVisibleVoiceEntries()` instead of `iterator.CurrentVoiceEntries`.
Also added a test which will fail if changes in `Cursor.ts` are reverted.

Add fix for cursor.next() when an instrument or voice is hidden

---

external/vexflow/vexflow.d.ts
src/MusicalScore/Graphical/BoundingBox.ts
src/MusicalScore/Graphical/EngravingRules.ts
src/MusicalScore/Graphical/MusicSheetCalculator.ts
src/MusicalScore/Graphical/SkyBottomLineCalculator.ts
src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetCalculator.ts
src/MusicalScore/ScoreIO/MusicSymbolModules/ExpressionReader.ts
src/MusicalScore/VoiceData/Expressions/InstantaneousTempoExpression.ts

add a graphical metronome mark (e.g. `<symbol of note> = 60`).
updates skyline to prevent lyricist collision

Graphical metronome mark

---

src/MusicalScore/Graphical/MusicSystemBuilder.ts
src/MusicalScore/Graphical/SystemLinesEnum.ts
src/MusicalScore/Graphical/VexFlow/VexFlowMeasure.ts
src/MusicalScore/ScoreIO/InstrumentReader.ts
src/MusicalScore/VoiceData/SourceMeasure.ts

Starts to add support for bar-style
Note: changes need to be made to VexFlow for these to be complete.
Example: 46a-Barlines.xml from the [Unofficial MusicXML Test Suite](http://lilypond.org/doc/v2.18/input/regression/musicxml/collated-files#t_g46-_002e_002e_002e-barlines-measures).
Measure 6 has `[bar-style=light-light]`, measure 7 `[bar-style=light-heavy]`

* Bar Lines: Add support for ending bar line styles

---

src/MusicalScore/Graphical/EngravingRules.ts
src/MusicalScore/Graphical/MusicSheetCalculator.ts
src/OpenSheetMusicDisplay/OSMDOptions.ts
src/OpenSheetMusicDisplay/OpenSheetMusicDisplay.ts

Hello,
I have added a new feature I personally wanted, allowing to render a particular interval of measures. Now,  `MaxMeasureToDrawIndex` is already implemented. I simply wanted to add its opposite `MinMeasureToDrawIndex`.
There is one thing that I want to ask you, how should I handle the case where `MinMeasureToDrawIndex > MaxMeasureToDrawIndex` ? Currently, an exception `TypeError: this.graphicalMusicSheet.MusicPages[0] is undefined` is thrown automatically. Other than that, here is a screenshot of the feature in action.

Added feature `MinMeasureToDrawIndex`

---

src/MusicalScore/MusicSheet.ts
src/MusicalScore/ScoreIO/InstrumentReader.ts
src/MusicalScore/ScoreIO/MusicSheetReader.ts
src/MusicalScore/ScoreIO/MusicSymbolModules/ExpressionReader.ts
src/MusicalScore/VoiceData/SourceMeasure.ts

praisethemoon strikes once again with another PR. I personally needed such API to capture measure's tempo. 
Does this deprecate `this.osmd.sheet.userStartTempoInBPM`? Right now it has a different value (100) and I think it either must be deprecated, or inherits its value from BPM of the first measure. 
Any thoughts? 🎵

Saving measures' BPM and fix #557

---

src/OpenSheetMusicDisplay/OpenSheetMusicDisplay.ts
test/Common/OSMD/OSMD_Test.ts

This would allow updating the model in the sheet and rerendering the graphical sheet thereof, thus allowing mutations on the OSMD model instead of the graphical model directly. However, this still requires a full rerender.

Allow updating the graphical sheet from the music sheet

---

.eslintrc.yml
package.json

updated eslint-plugin-promise and eslint. eslint-plugin-import was updated earlier outside of the branch.
eslintrc: ecmaversion set to 8 to handle await/promises
tested, builds fine.

Update eslint dependencies

---

src/MusicalScore/Graphical/VexFlow/VexFlowConverter.ts

Conditional was added to ensure that TypeLength value did not override the duration improperly.
Duplicated from logic present for all smaller note values to accommodate half notes.
User provided sample now renders correctly:
Test task results:
[test_results.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4432980/test_results.txt)
One failure, but this also failed on a fresh copy of develop, so assuming it is environment related:
```
FAILED TESTS:
OpenSheetMusicDisplay Main Export
✖ load invalid URL
HeadlessChrome 80.0.3987 (Linux 0.0.0)
```
Visual regression test results:
[results.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4432974/results.txt)
```
Found 41 current and 41 blessed png files (not tested if valid). Continuing.\n
Running …
```

#700, Rendering fix for half note tuplets

---

src/MusicalScore/Graphical/EngravingRules.ts
src/MusicalScore/Graphical/VexFlow/VexFlowMeasure.ts

Skyline will now be adjusted to take into account volta repetition endings.
If the volta would be rendered in conflict with other elements, the skyline is recalculated to avoid this.
Additionally the engraving rule for volta offset is now available for use, with a good default value provided.
Finally, some initial boilerplate code is present for a related feature that we discussed, but is not functional yet and is commented out:
Setting pairs of voltas to the same height.
extra-compact view PDF w/ Skyline (using provided JS console code):
[Scott Joplin Elite Syncopations.pdf](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4619213/Scott.Joplin.Elite.Syncopations.pdf)
Standard view PDF w/ Skyline:
[Scott Joplin Elite …

Bugfix/#741 - Fix skyline generation for Volta repetition endings

---

src/MusicalScore/Graphical/DrawingParameters.ts
src/MusicalScore/Graphical/EngravingRules.ts
src/MusicalScore/Graphical/MusicSystemBuilder.ts
src/OpenSheetMusicDisplay/OpenSheetMusicDisplay.ts

Optimize vertical distance between staff lines.
This lets staff lines be closer in distance by checking every point in a staffline's skyline for collisions with the skyline of the next staffline. This way, even if the lowest bottomline value of a staffline overlaps the highest skyline value of the next staffline, they can still be moved closer beyond this previous limitation, if the skylines don't cross at a specific location. [sschmidTU]
Added new parameter for customizing vertical layout.
implementation by @buenaflor , thank you very much!
I will now check these changes with [visual regression tests etc.](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Testing), looks good so far!

Optimize staff lines distance using SkyBottomline intersections

---

src/MusicalScore/Graphical/EngravingRules.ts
src/MusicalScore/Graphical/GraphicalCurve.ts
src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetDrawer.ts

Test results:
[test_results.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4717967/test_results.txt)
Visual Results:
[results.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4717954/results.txt)
Differences seem to be related to spacing based on incorrect skyline, with current being more compact.

Fix skyline not being calculated for slurs properly

---

src/MusicalScore/Graphical/GraphicalSlur.ts

Implemented placing the slurs on the side of the noteheads if start- and end-note have the same stemdirection.
Please check for slur changes in the visuals.

Fix: Implemented placing the slurs on the side of the noteheads 

---

src/MusicalScore/ScoreIO/MusicSymbolModules/ExpressionReader.ts

...as the dynamic expression might make sense for e.g. a repetition start, where another dynamic was used at the end of the repetition.
We could implement this check as a afterSheetReadingModule when we know all Repetitions and Expressions..

fix: removed doublettes check for dynamic expressions

---

src/MusicalScore/Graphical/GraphicalContinuousDynamicExpression.ts
src/MusicalScore/Graphical/SkyBottomLineCalculator.ts

diminuendo lines direction needed reversed for skyline/bottom line calculation. 
These are now calculated correctly in OSMD test files:

Fix for diminuendo wedges

---

src/MusicalScore/Graphical/AbstractGraphicalExpression.ts
src/MusicalScore/Graphical/GraphicalContinuousDynamicExpression.ts
src/MusicalScore/Graphical/GraphicalInstantaneousDynamicExpression.ts
src/MusicalScore/Graphical/GraphicalInstantaneousTempoExpression.ts
src/MusicalScore/Graphical/GraphicalUnknownExpression.ts
src/MusicalScore/Graphical/MusicSheetCalculator.ts
src/MusicalScore/Graphical/VexFlow/AlignmentManager.ts
src/MusicalScore/Graphical/VexFlow/VexFlowContinuousDynamicExpression.ts
src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetCalculator.ts
src/MusicalScore/ScoreIO/MusicSymbolModules/ExpressionReader.ts
src/MusicalScore/VoiceData/Expressions/AbstractExpression.ts
src/MusicalScore/VoiceData/Expressions/ContinuousExpressions/ContinuousDynamicExpression.ts
src/MusicalScore/VoiceData/Expressions/InstantaneousDynamicExpression.ts

manual merge of #768 
fixes #758
fixes some heavy y shifting of expressions (e.g. "dim." in Beethoven Geliebte going into next staffline)
fixes skyline/bottomline when GraphicalUnknownExpressions are involved, which don't have an AbstractExpression, so expression.Placement crashed, even with null check.
we should probably have one visual regression test which adds skyline and bottomline, makes it easier to spot regressions for these. will be done next.
visual regression tests show only positive changes, except for the Expressions - Overlap sample.
But this is less important than the new improvements.
I'm actually not sure how this was solved originally, because i can find no direct y collision checking code for expressions.

Fix expression y shift, skyline for UnknownExpression

---

src/MusicalScore/Graphical/EngravingRules.ts
src/MusicalScore/Graphical/MusicSystemBuilder.ts
src/MusicalScore/ScoreIO/InstrumentReader.ts
src/MusicalScore/ScoreIO/MusicSheetReader.ts
src/MusicalScore/VoiceData/SourceMeasure.ts

implemented showing the current rhythm in any case if there was an end line given in the last system.

fix: show rhythm in first system measure, if last system ended with end-barline

---

src/MusicalScore/Graphical/MusicSheetCalculator.ts

The staffline offset was only being taken into account for the first staffline. Removed this check.
The visual diff seems to be only related to the measure numbers and some spacing as a result of that:
[visual_diff.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4745793/visual_diff.zip)
Karma results:
[test_results.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4745794/test_results.txt)

Fix measure number skyline offset

---

demo/index.js
src/MusicalScore/Graphical/GraphicalSlur.ts
test/data/Slurtest_highNotes.musicxml

Fix reference issue with variables. Slurs now avoid colliding with notes properly
Visual diff results (seems just related to slurs as would be expected):
[visual_diff_results.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4805837/visual_diff_results.zip)
Test results:
[test_results.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4805840/test_results.txt)
NOTE: Slurs still need optimization

Slurs Avoid note Collision

---

.gitignore
package.json

@sschmidTU,
I think this is a good option to have, let me know if you think there are any issues with having this included in the codebase.
Specifically, I needed to add the 'allowedHosts' option with a custom entry for my local environment. I can imagine other local-specific environment options could exist for other developers as well.

Add option for untracked local env config file

---

src/MusicalScore/Graphical/VexFlow/VexFlowMeasure.ts
src/MusicalScore/Graphical/VexFlow/VexFlowMusicSystem.ts

If single system line, and repeat is at beginning (but offset due to clef etc.) do not render opening single barline.
So for example, this:
Will now render like this:
But multiple stafflines will still have their line (which is present regardless of repeat), like so:
Visual test results:
[visual-results.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4948113/visual-results.txt)
Karma test results:
[test-results.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/4948115/test-results.txt)

fix(repeat): Override VF behavior for repeats at system beginning

---

src/MusicalScore/Graphical/VexFlow/VexFlowConverter.ts
src/MusicalScore/Graphical/VexFlow/VexFlowGraphicalNote.ts
src/MusicalScore/ScoreIO/VoiceGenerator.ts
src/MusicalScore/VoiceData/Note.ts

Fix #759 
I added the xml node the the Note.ts class. Now it get's the information if there is a repositioning of the rest in y direction. @sschmidTU I stumbled upon an old FIXME where you noticed, that we shift the octave by +3 in case of notes. It seems to depend on the clefs in case of rests also. Any idea what that might be? Some vexflow magic?

fix(rest note y positions): Rest notes respect the display-step and display-octave tags now

---

demo/index.js
src/MusicalScore/Graphical/EngravingRules.ts
src/MusicalScore/Graphical/GraphicalMeasure.ts
src/MusicalScore/Graphical/MusicSheetCalculator.ts
src/MusicalScore/VoiceData/SourceMeasure.ts
src/OpenSheetMusicDisplay/OSMDOptions.ts
src/OpenSheetMusicDisplay/OpenSheetMusicDisplay.ts
test/data/Test_Auto_Multirest_1.musicxml
test/data/Test_Auto_Multirest_2.musicxml

Test results:
[test_results.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5056980/test_results.txt)
Visual diff results:
[visual_results.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/5056981/visual_results.txt)
Added two test files.
One question:
This setting is set to on by default; Perhaps we should default to off? Not sure.

Auto-generate multirest from subsequent rest-only measures

---

src/Common/DataObjects/Fraction.ts

The `greatestCommonDenominator` function has no guard against non-convergence due to floating-point errors and this causes loading of some musicxml docs to spin forever in the for loop.
Basically, in some cases `b` becomes very small (< `2.0e-14`) and never converges to 0.

Certain xml docs cause hang when loading

---

src/OpenSheetMusicDisplay/OSMDOptions.ts

Related to https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/pull/879. Documents the behavior described by  https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/541#issuecomment-687360793 correctly in the code in case someone goes looking.

Fix doc comment for useXMLMeasureNumbers option

---

src/MusicalScore/Graphical/GraphicalLine.ts
src/MusicalScore/Graphical/MusicSheetDrawer.ts
src/MusicalScore/Graphical/VexFlow/CanvasVexFlowBackend.ts
src/MusicalScore/Graphical/VexFlow/SvgVexFlowBackend.ts
src/MusicalScore/Graphical/VexFlow/VexFlowBackend.ts
src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetDrawer.ts

This makes it possible to remove drawn elements without re-rendering (SVG only).
```js
const node = osmd.drawer.DrawOverlayLine({x: 32,y: 20},{x: 34,y: 20},osmd.graphic.MusicPages[0]);
osmd.drawer.backend.removeNode(node);
```
methods returning node(s):
drawLine
drawRectangle
drawBoundingBox
drawLabel (returns node array, a node for each line / text)
see also #969 for drawBoundingBox() etc

Feat: RenderRectangle etc returns removable node, add backend.removeNode()

---

src/Common/DataObjects/Pitch.ts
src/MusicalScore/Graphical/VexFlow/VexFlowConverter.ts
src/MusicalScore/ScoreIO/MusicSymbolModules/ArticulationReader.ts

I made a new PR with just the three-quarter flats and shaps and without the turkish accidentals until I investigate further how they are meant to be represented in musicXML.
I also renamed the triple-sharp from `++` to `###` so that it doesn't collide with the naming of the three-quarter sharp.

Added support for three-quarter flats and sharps

---

src/OpenSheetMusicDisplay/Cursor.ts

In single-line rendering, the cursor is always set to block:center, which will cause the vertical axis to be centered, but users may have their own needs, so block should not be set during single-line rendering, but inline needs to be set to follow cursor

Adapt the cursor to single line and multiple lines

---

src/MusicalScore/Graphical/GraphicalMusicSheet.ts

handle undefined parentStaffEntry in GraphicalMusicSheet.GetNearestVoiceEntry
issue [1029](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/1029), fix suggested by @conde2. Please merge if appropriate.

handle undefined parentStaffEntry

---

src/MusicalScore/Graphical/VexFlow/VexFlowVoiceEntry.ts

This null check is needed for some scores - the stavenote is null and the score simply doesn't render due to the exception being thrown.
Visual results:
[visual-results.txt](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/6792482/visual-results.txt)
test results:
[test.log](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/6792487/test.log)

Null check for stavenote on color method

---

.eslintrc.js
demo/index.js
src/MusicalScore/Graphical/EngravingRules.ts
src/MusicalScore/Graphical/GraphicalMeasure.ts
src/MusicalScore/Graphical/GraphicalStaffEntry.ts
src/MusicalScore/Graphical/MusicSheetCalculator.ts
src/MusicalScore/Graphical/VexFlow/VexFlowMeasure.ts
src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetDrawer.ts
src/MusicalScore/VoiceData/Expressions/AbstractExpression.ts
test/data/test_Fingerings_Simple_Chords_Treble_Bass.musicxml

before: (left / FingeringPositionFromXML)
after: (AboveOrBelow, FingeringPositionFromXML)
[test_Fingerings_Simple_Chords_Treble_Bass.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/7516089/test_Fingerings_Simple_Chords_Treble_Bass.zip)
visual diffs:
[diffs_fingering_above_below_collision_fix2.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/7516223/diffs_fingering_above_below_collision_fix2.zip)
a valid alternative to the new above/below default, also to save space, is left (or right) positioning:
```js
osmd.EngravingRules.FingeringPosition = 2; // PlacementEnum.Left
osmd.EngravingRules.FingeringPositionFromXML = false; // otherwise an XML placement 'below' will put fingering for those notes below
```

Fix Fingering collisions (#1081), make Above/Below default position

---

src/MusicalScore/Graphical/EngravingRules.ts
src/MusicalScore/Graphical/MusicSheetCalculator.ts
test/data/test_chord_symbols_collision_high_notes_alignment.musicxml

See https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/934#issuecomment-966392856.
Before/After:
measure wide alignment option is available, but staffline is default.
Alignment can also be turned off completely:

Fix chord symbol collisions with notes and add alignment to staffline (or measure)

---

src/VexFlowPatch/src/stavenote.js
test/data/test_note_overlap_staggering.musicxml
test/data/test_note_overlap_staggering_quarter.musicxml

Fix #1098
No visual regressions.
This should be caught by our tests though (there should have been a visual diff), so I've added the sample `test_note_overlap_staggering` to the visual regression tests.
@rvilarl FYI, this is an improvement on the Vexflowpatch for stavenote.js, though I believe the notes are correctly staggered in Vexflow 4 anyways, see #1098.

Fix notes overlapping / not staggering

---

src/MusicalScore/ScoreIO/VoiceGenerator.ts
src/MusicalScore/VoiceData/Tie.ts
test/data/test_ties_missing_1097.musicxml

Fixes #1097
The tie handling had a few bugs where ties were deleted or overwritten, or a "start" `tied` given before a "stop" `tied` in XML leading to new ties started before the old one was "closed" (removed from openTieDict).

Fix ties missing (#1097)

---

src/MusicalScore/Graphical/GraphicalTie.ts
src/MusicalScore/Graphical/MusicSheetDrawer.ts
src/MusicalScore/Graphical/VexFlow/CanvasVexFlowBackend.ts
src/MusicalScore/Graphical/VexFlow/SvgVexFlowBackend.ts
src/MusicalScore/Graphical/VexFlow/VexFlowBackend.ts
src/MusicalScore/Graphical/VexFlow/VexFlowConverter.ts
src/MusicalScore/Graphical/VexFlow/VexFlowGraphicalNote.ts
src/MusicalScore/Graphical/VexFlow/VexFlowGraphicalSymbolFactory.ts
src/MusicalScore/Graphical/VexFlow/VexFlowInstrumentBrace.ts
src/MusicalScore/Graphical/VexFlow/VexFlowInstrumentBracket.ts
src/MusicalScore/Graphical/VexFlow/VexFlowMeasure.ts
src/MusicalScore/Graphical/VexFlow/VexFlowMultiRestMeasure.ts
src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetCalculator.ts
src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetDrawer.ts
src/MusicalScore/Graphical/VexFlow/VexFlowOctaveShift.ts
src/MusicalScore/Graphical/VexFlow/VexFlowSlur.ts
src/MusicalScore/Graphical/VexFlow/VexFlowStaffEntry.ts
src/MusicalScore/Graphical/VexFlow/VexFlowTabMeasure.ts
src/MusicalScore/Graphical/VexFlow/VexFlowVoiceEntry.ts
src/MusicalScore/VoiceData/Arpeggio.ts

Corresponds to Vexflow 4 usage.
also makes the diff to the vexflow 4 branch much clearer,
because there aren't thousands of lines just changing Vex.Flow to VF.

refactor: change all occurences of Vex.Flow to VF

---

src/MusicalScore/ScoreIO/VoiceGenerator.ts
src/MusicalScore/VoiceData/Staff.ts

extended issue 51
This moves openTieDict from VoiceGenerator to Staff. That's because a different VoiceGenerator is generated for each voice (and staff), and each has its own openTieDict, so it is assumed that tie notes are all in the same voice. That may be the correct way to do it in MusicXML, but in practice, tie notes in MusicXML can be in different voices.
So we manage ties in Staff now instead of the VoiceGenerator, so ties are per Staff, not per Voice.
No visual regressions.
Fixes `osmd.graphic.MeasureList[3][0].staffEntries[0].graphicalVoiceEntries[0].notes[0].sourceNote.NoteTie` undefined in Clair de Lune.
[clair.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/8125443/clair.zip)

fix(Ties): Fix note.NoteTie undefined for tie end note in different voice than start note

---

src/MusicalScore/Graphical/EngravingRules.ts
src/MusicalScore/VoiceData/ChordSymbolContainer.ts

This PR replaces "b", "#" and "x" chord accidentals with their more accurate counterparts "♭", "♯" and "𝄪". This helps clarify the chord display, as per attached screenshot.

Chord accidentals

---

package.json
test/Util/generateImages_browserless.mjs

The `gl` npm package added by PR #1158 is hard to install. This PR is to move `gl` to `optionalDependencies` so the developers can install OSMD easily as before. Before merging this PR, I want to find the exact circumstances under which `gl` can be installed. In addition, I think now is the time to add instructions about the batch and the WebGL visual regression tests to [the wiki](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/wiki/Testing#visual-regression-tests-unixmacwsl2-only-for-now).
I've tested Windows 10 using the Windows Sandbox, and it seems like `gl` can be installed without Python 2 or Visual C++ (which is contrary to [the docs](https://www.npmjs.com/package/gl#system-dependencies)). I will add test results for macOS or Ubuntu as well.
(+ Update) It seems like …

Move `gl` to `optionalDependencies`

---

src/MusicalScore/Graphical/PlainSkyBottomLineBatchCalculatorBackend.ts
src/MusicalScore/Graphical/SkyBottomLineBatchCalculatorBackend.ts
src/MusicalScore/Graphical/VexFlow/VexFlowMeasure.ts
src/MusicalScore/Graphical/WebGLSkyBottomLineBatchCalculatorBackend.ts

to lessen merge conflicts with feat/vexflow4 branch
visual regression tests pass.
a few of the changes couldn't be transferred because vexflow 1 doesn't have the methods or our definitions are incomplete, so we need to use `any`.
I'm preparing a PR to DefinitelyTyped to add these, because it would be much cleaner and less annoying to not use `any` when these methods/accessors are standard and public, but just missing in these definitions.
examples: stave.setNumLines(), stave.options, timesignature.setStyle(), stave.endClef/stave.getEndClef()

refactor: merge changes from feat/vexflow4 branch (#1139) (style changes etc)

---

src/MusicalScore/Graphical/EngravingRules.ts
src/MusicalScore/Graphical/MusicSheetCalculator.ts
src/MusicalScore/Graphical/VexFlow/VexFlowMeasure.ts
src/MusicalScore/VoiceData/Tuplet.ts
src/VexFlowPatch/readme.txt
src/VexFlowPatch/src/tuplet.js
test/data/test_tuplet_consecutive_3and5_tuplets.musicxml
test/data/test_tuplet_consecutive_simple.musicxml
test/data/test_tuplet_consecutive_simple_alwaysdisable.musicxml

closes #1207 (see there for info)
add `EngravingRules.TupletNumberLimitConsecutiveRepetitions` (default true)
add `EngravingRules.TupletNumberMaxConsecutiveRepetitions` (default 2)
add `EngravingRules.TupletNumberAlwaysDisableAfterFirstMax` (default true)
add 3 test samples
add vexflow patch to add option for tuplets not to render their tuplet number
running visual regression tests now

feat(Tuplets): Add EngravingRules.TupletNumberLimitConsecutiveRepetitions (default true) etc. (breaking change)

---

src/MusicalScore/Graphical/EngravingRules.ts
src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetCalculator.ts

before:
after:
visual diffs after aed4bba34190ca09709948953861b7cd474d7ce7:
[diff_implicit-spacing.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/9620019/diff_implicit-spacing.zip)
(only Mozart Clarinet Quintet taking very slightly more space, but giving the implicit measure a nice bit of additional space too)

Fix implicit measure spacing

---

src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetCalculator.ts

Fixes #1281
no visual regressions.

Fix octaveshift error when startX greater stopX

---

src/MusicalScore/Graphical/EngravingRules.ts
src/MusicalScore/Graphical/VexFlow/VexFlowConverter.ts
src/MusicalScore/ScoreIO/MusicSymbolModules/ArticulationReader.ts
src/VexFlowPatch/readme.txt
src/VexFlowPatch/src/articulation.js
test/data/test_breath_mark.musicxml

breath mark wasn't previously shown:
`test_breath_mark.musicxml`
New EngravingRule `BreathMarkDistance`: % distance to next note or end of staff. default 0.8 = 80% distance towards next note/staff.
no visual regressions.
-----
In future, we could support a different common symbol for a breath mark, a sort of `v`/upbow (but apparently slightly different to the upbow glyph), here in Musescore:
glyphs from Vexflow 1.2.93 tables.js:
```js
breathMarkComma: 'v6c',
breathMarkUpbow: 'v8a', // looks better than current upbow
```

breath mark support

---

src/MusicalScore/Graphical/MusicSheetCalculator.ts
src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetCalculator.ts
src/MusicalScore/Instrument.ts
src/MusicalScore/ScoreIO/MusicSymbolModules/LyricsReader.ts
src/MusicalScore/VoiceData/Lyrics/LyricsEntry.ts
src/MusicalScore/VoiceData/VoiceEntry.ts

Changed the lyrics verse numbers from type number to type string according to the MusicXML specification. This fixes a lot of issues when importing MusicXML files that were created with Dorico or Sibelius. When using Dorico, refrain/chorus and translations are now recognized and rendered in italics. Issues #1271 and #1272 are fixed now and lyrics with non-numeric identifiers are no longer rendered on top of the staffs.

Improved lyrics handling

---

src/MusicalScore/Graphical/MusicSheetCalculator.ts
test/data/test_tuplet_consecutive_respect_notelength.musicxml

See https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/1207#issuecomment-1398816426
This could be expanded to check not only the first note but all notes, but that would complicate the code a bit and should be rarely needed.
Aside from the new sample, the few visual diffs are mostly a matter of taste, and depend on options set.
[diff_tuplet_consecutive_length.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/10469391/diff_tuplet_consecutive_length.zip)

Fix consecutive tuplet label number disabling not respecting note length

---

src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetCalculator.ts
test/Util/generateImages_browserless.mjs
test/data/test_octaveshift_extragraphicalmeasure.musicxml

also fix octaveshift bbox width negative
evolution of PR #1376 (thanks for the report @taiyungwang)
Fixes this octave shift erroring because the last measure in the staffline is an extra graphical measure (for key/rhythm change):
sample:
[Chopin_-_Nocturne_Op_9_No_2_E_Flat_Major.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/11491544/Chopin_-_Nocturne_Op_9_No_2_E_Flat_Major.zip)
The method used for finding the last measure in the staffline was naive, simply taking the last one in the staffline, which can have IsExtraGraphicalMeasure = true, no staffentries, and measure number -1.
OctaveShift needs a staffentry in the measure to determine the stopping position. (This could also be changed, then we can also stop the octaveshift at an ExtraGraphicalMeasure, would …

Fix octaveshift end note not found if last staffline measure IsExtraGraphicalMeasure (error)

---

src/MusicalScore/Graphical/MusicSheetCalculator.ts
src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetCalculator.ts
src/MusicalScore/VoiceData/SourceStaffEntry.ts
test/data/test_decrescendo_crescendo_stop_start.musicxml

Fixes #1404 (see examples there)
All the visual diffs in the visual regression tests are good or at least not bad.
There are a few cases where we might not always want to start the wedge that far to the left, but it's also not really an issue.
That might be a case for fine-tuning later on in another PR.
(e.g. `Debussy Mandoline` measure 10. Though it'll be hard to isolate the conditions for this, as `Gretchaninov - A Boring Story` measure 8 when starting on a new line/system is a similar condition (start of measure/system, first note) and looks better now.)
Also, we might not want to have wedges starting on grace notes visually, though maybe we actually do (e.g. `Beethoven Geliebte` measure, MuseScore doesn't start from the grace note, but maybe they're wrong).
One odd issue that should …

Fix wedges, crescendo etc start x and end x

---

src/MusicalScore/Graphical/EngravingRules.ts
src/MusicalScore/Graphical/GraphicalLabel.ts
src/MusicalScore/Graphical/GraphicalLyricEntry.ts
src/MusicalScore/Graphical/MusicSheetCalculator.ts
test/data/test_lyrics_centering.musicxml

Fix short lyrics not looking vertically centered below notes. Fix dash overlap in short intervals

---

src/MusicalScore/Graphical/MusicSystemBuilder.ts
src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetCalculator.ts
src/VexFlowPatch/src/stave.js
test/data/test_noteStartX_key_signatures.musicxml

Fixes #1425. #1315
before:
after:
new sample: `test_noteStartX_key_signatures.musicxml`
<details><summary>before:</summary>
</details>
after:
`Mozart_Clarinet_Quintet_Excerpt.mxl`
<details><summary>before:</summary>
</details>
after:
(sample from #1425)
The Brandenburg concerto, a very big score, is now also correctly aligned, very pleased!
<details><summary>before:</summary>
</details>
after:
edit: This fix is an extended version of the one Vexflow did in their repository:
https://github.com/0xfe/vexflow/pull/1390
In our case, this fix alone was not enough, because of how we use `formatToStave()`, which overwrote the new `x` and `start_x` values after they had been set correctly. (which was quite tricky to debug)

Fix note x-alignment for staves with different key signatures

---

src/MusicalScore/Graphical/VexFlow/VexFlowConverter.ts
src/MusicalScore/VoiceData/Notehead.ts
src/VexFlowPatch/readme.txt
src/VexFlowPatch/src/notehead.js
src/VexFlowPatch/src/stavenote.js
src/VexFlowPatch/src/tables.js
test/data/test_notehead_inverted_triangle_stem_down.musicxml
test/data/test_notehead_inverted_triangle_stem_up.musicxml

Fix #1418
[test_notehead_inverted_triangle_stem_up_down.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/12051266/test_notehead_inverted_triangle_stem_up_down.zip)
Note that the x and y positioning especially for the smaller notes isn't ideal, but hard to optimize. If we e.g. shift everything one more pixel, the triangle of the small notes is not well visible, basically "eaten up" by the stem, or not connected to it. There are some intricacies of the glyph code here because this is a custom glyph that wasn't originally supported by Vexflow, so without a real deep dive into the custom glyph code, I think this is as far as we can go right now. Probably the x-shift would need to scale with note scaling.
visual diffs: …

Support inverted triangle notehead

---

src/MusicalScore/Graphical/GraphicalMusicSheet.ts
src/OpenSheetMusicDisplay/Cursor.ts

after:
before:
after:
before:
```js
osmd.Sheet.Instruments[0].Visible = false;
osmd.cursor.cursorOptions.type = 3
```

Fix cursor type 3 when first measure(s) invisible

---

src/MusicalScore/Graphical/VexFlow/VexFlowConverter.ts
src/MusicalScore/ScoreIO/VoiceGenerator.ts
src/VexFlowPatch/readme.txt
src/VexFlowPatch/src/formatter.js

* Fix error because x is NaN due to some faults in specific tab MusicXML files
* Fix error when string number and fret number are not provided in a MusicXML file, even though they always should be for non-rest notes. Report/log that these are missing instead.
reported by mimimix on Discord in the sponsor-dev channel
(sample `BORN_UNDER_A_BAD_SIGN_2.musicxml`)

Fix tab errors for faulty xml files

---

src/MusicalScore/Graphical/GraphicalContinuousDynamicExpression.ts
src/MusicalScore/Graphical/MusicSheetCalculator.ts
test/Util/generateImages_browserless.mjs
test/data/test_wedge_multiline_crescendo.musicxml
test/data/test_wedge_multiline_decrescendo.musicxml

Fixes #1277
before:
after:
same for decrescendo / diminuendo.
visual regression diffs:
[diff_wedge-multiline-total-diff-pr-1459.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/12648203/diff_wedge-multiline-total-diff-pr-1459.zip)
(using the new generateImages version, and adding the new samples)

Fix multiline wedges missing in-between staffline wedges

---

src/MusicalScore/ScoreIO/MusicSymbolModules/ExpressionReader.ts
test/data/test_bold_italic.musicxml

refactor of PR #1483 (thanks @fablau !)
after:
before:
No visual regressions / changes in existing samples, so I added this new sample `test_bold_italic.musicxml`.

Fix BoldItalic read as Bold instead of BoldItalic

---

src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetDrawer.ts

Small fix for #1413 
Looks like SVG export doesn't always have bounding boxes for the SVG elements.
(probably due to how we fake the browser environment / DOM in the generateImages script)
The error was `(...).getBbox() is not a function`

fix(Buzz Roll): Fix error in SVG export for buzz rolls

---

src/MusicalScore/Graphical/MusicSheetCalculator.ts
test/data/test_wedge_cresc_dim_simultaneous_quartet.musicxml
test/data/test_wedge_crescendo_multi-instrument.musicxml
test/data/test_wedge_decrescendo_crescendo_stop_start.musicxml
test/data/test_wedge_decrescendo_multi-instrument_startX.musicxml

Additional fix for #1480, that fixes a similar problem in a new sample that we weren't aware of before.
Before:
After:
Basically no visual regressions, except in `test_wedge_crescendo_multi-instrument` the wedges are now better vertically aligned.
visual regressions:
[diff_wedge_startx-fix.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/14102274/diff_wedge_startx-fix.zip)
(had to rename a few images in the blessed sample, since the sample name changed)
Added new sample `test_wedge_decrescendo_multi-instrument_startX.musicxml`
Thanks to boblete for the report and sample!

Fix (decrescendo) wedge startX in multi-instrument scores (further)

---

src/MusicalScore/Graphical/EngravingRules.ts
src/MusicalScore/Graphical/VexFlow/VexFlowMeasure.ts
src/MusicalScore/Graphical/VexFlow/VexFlowTabMeasure.ts
src/MusicalScore/VoiceData/Note.ts
src/MusicalScore/VoiceData/TabNote.ts
src/MusicalScore/VoiceData/Tuplet.ts
test/data/test_tab_x-alignment_triplet_plus_bend.musicxml
test/data/test_tab_x-alignment_triplet_plus_bracket_below_above.musicxml

before:
after:
tuplet brackets can be disabled like this:
```js
osmd.EngravingRules.TupletNumbersInTabs = false;
// or just show the tuplet number without the bracket:
osmd.EngravingRules.TabTupletsBracketed = false;
```
tuplet brackets are placed below by default, unless there's a placement tag in the XML.
This is somewhat related to #1062 and #1489, though it's a different cause and part of the code.

Fix tab tuplet / triplet x-alignment, tab tuplet brackets

---

src/MusicalScore/Graphical/MusicSheetCalculator.ts
src/MusicalScore/ScoreIO/InstrumentReader.ts
src/MusicalScore/VoiceData/SourceMeasure.ts
src/OpenSheetMusicDisplay/OSMDOptions.ts
test/data/Beethoven_AnDieFerneGeliebte.xml

Adds widthFactor for individual measures (osmdWidthFactor), first part of #1534.
(second part will be global scale factor for all measures)
e.g.:
```xml
<measure number="1" osmdWidthFactor="0.7"/>
```
This will make measure 1 only 70% as wide as OSMD would make it otherwise.
after:
before:
You can also set this factor manually in SourceMeasure.widthFactor:
```js
osmd.Sheet.SourceMeasures[0].widthFactor = 0.7;
osmd.render();
```
We will also soon add a similar attribute for a global scale factor `x` that will scale all measure widths by `x`.
Note that if you make the factor too low (shrink measures too much), there might be overlaps and other layout issues, especially with lyrics. So use this with caution and at your own risk ;)

Add SourceMeasure.widthFactor, parse osmdWidthFactor attribute from xml

---

src/MusicalScore/Graphical/GraphicalLine.ts
src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetDrawer.ts

Added SVGelement property to GraphicalLine to be consistent with grap…hicalSlurs

Added SVGelement property to GraphicalLine

---

src/MusicalScore/MusicParts/MusicPartManagerIterator.ts

Function returns before checking other voice entries for the same `instrument.idString`.  
repro:
Choose any score with instruments having more than one voice, e.g. _An die Ferne Geliebete_ and compare the results of
`osmd.cursor.VoicesUnderCursor().filter(voice => voice.parentVoice.parent.idString === osmd.sheet.instruments[1].idString)` 
against
`osmd.cursor.VoicesUnderCursor(osmd.sheet.instruments[1])`.
Before change:
After change:

Fix MusicPartManagerIterator.CurrentVisibleVoiceEntries() not filtering by instrument correctly.
