Gruntfile.js, demo/demo.js, demo/index.html, demo/inject.ts, karma.conf.js, package.json, src/OSMD/OSMD.ts, typings.json
=> Added build configuration to allow use of OpenSheetMusicDisplay via script tag

src/MusicalScore/Graphical/VexFlow/VexFlowConverter.ts, test/MusicalScore/ScoreIO/Key_Test.ts, test/data/HelloWorld.xml
Deals with #108 
Enables loading of MusicXMLs with the optional `mode` element missing.
=> [feature] Optional key signature

src/MusicalScore/Graphical/EngravingRules.ts
It can be usefull to change  this right margin. 
In my personal case, i need it.
=> Can now change system labels right margin

Gruntfile.js, package.json, webpack.config.js
I also added a basic webpack dev server setup. It points to the demo.js in the demo folder and fires up the index.html if started. I did NOT change any code there because I didn't want to mess around too much. However I find it very convenient to use the dev server for server the files directly for fast hot loading debugging.
=> Moved webpack configuration to seperate file, issue #103

src/MusicalScore/VoiceData/Instructions/KeyInstruction.ts
=> Completing the Key Mode enum according to MusicXML

package.json, src/MusicalScore/Graphical/MusicSystem.ts, src/MusicalScore/Graphical/StaffLine.ts, src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetDrawer.ts, src/MusicalScore/ScoreIO/InstrumentReader.ts, src/MusicalScore/ScoreIO/VoiceGenerator.ts, src/MusicalScore/VoiceData/VerticalSourceStaffEntryContainer.ts, src/OSMD/Cursor.ts
Fixes #176 
TypeScript 2.6 enforces a higher level of code quality, so unused fields are detected earlier. I made the following changes to allow us upgrading to the latest TypeScript version. 
@matt-uib @bukaznik cc please review, but let me merge myself, I need to squash these changes and adapt commit message accordingly.
=> Update to TypeScript 2.6.1

demo/index.html, demo/index.js, package.json, src/MusicalScore/Graphical/MusicSheetDrawer.ts, src/MusicalScore/Graphical/VexFlow/VexFlowInstrumentBracket.ts, src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetDrawer.ts, src/MusicalScore/Graphical/VexFlow/VexFlowMusicSystem.ts, webpack.config.js
Frohe Weihnachten :) Implemented issue #64
=> Added instrument brace/bracket

package.json
=> chore(package): update @types/mocha to version 5.2.3

external/vexflow/vexflow.d.ts, src/MusicalScore/Graphical/MusicSheetCalculator.ts, src/MusicalScore/Graphical/VexFlow/VexFlowConverter.ts, src/MusicalScore/Graphical/VexFlow/VexFlowInstrumentBracket.ts, src/MusicalScore/Graphical/VexFlow/VexFlowMeasure.ts, src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetCalculator.ts, src/MusicalScore/ScoreIO/InstrumentReader.ts, src/MusicalScore/ScoreIO/VoiceGenerator.ts, src/MusicalScore/VoiceData/Note.ts, src/MusicalScore/VoiceData/VoiceEntry.ts
=> feat(color): color notes/stems by XML

package.json
=> chore(package): update webpack to version 4.25.0

src/MusicalScore/Graphical/GraphicalStaffEntry.ts
=> RelativePosition.Y => RelativePosition.y

src/OpenSheetMusicDisplay/Cursor.ts, src/OpenSheetMusicDisplay/OpenSheetMusicDisplay.ts
=> Grant read access to osmd and cursor member elements

demo/index.js, src/MusicalScore/Graphical/DrawingEnums.ts, src/MusicalScore/Graphical/DrawingParameters.ts, src/MusicalScore/Graphical/EngravingRules.ts, src/MusicalScore/Graphical/GraphicalVoiceEntry.ts, src/OpenSheetMusicDisplay/OSMDOptions.ts, src/OpenSheetMusicDisplay/OpenSheetMusicDisplay.ts, test/data/Alle-meine-Entchen-XML.xml, test/data/OSMD_function_test_auto-custom-coloring-entchen.musicxml, test/data/OSMD_function_test_color.musicxml
=> feat(COloring): Added automatic Boomwhacker coloring scheme

src/OpenSheetMusicDisplay/Cursor.ts, test/Common/OSMD/OSMD_Test.ts
Work in progress, please do not merge yet! Related to #448.
Added new methods in `Cursor` class:
- `get AllVoicesUnderCursor()`
- `VoicesUnderCursor(instrument?: Instrument)`
- `NotesUnderCursor(instrument?: Instrument)`
Also added tests.
=> WIP: Add methods to retreive notes and voices under cursor

package.json
=> chore(package): update mocha to version 6.2.0

demo/embedded_demo.html, demo/index.html, demo/index.js
- add parameter handler for embedded, controls, header and zoomControls
- add option to set zoom via parameter
- add feature to display compact zoomControl widget
=> Feature #576: Added basic support for iframe embedding

package.json
=> chore(package): update @types/mocha to version 7.0.1

package.json
=> chore(package): update @types/node to version 13.9.0

package.json
=> chore(package): update @types/node to version 13.9.1

package.json
=> chore(package): update @types/node to version 13.9.8

package.json
=> chore(package): update eslint-plugin-import to version 2.20.2

demo/index.js, src/MusicalScore/Graphical/VexFlow/VexFlowMeasure.ts, src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetCalculator.ts, src/OpenSheetMusicDisplay/OpenSheetMusicDisplay.ts
=> Fix beams retaining slope when zooming

src/MusicalScore/Graphical/AbstractGraphicalExpression.ts, src/MusicalScore/Graphical/GraphicalUnknownExpression.ts, src/MusicalScore/Graphical/MusicSheetCalculator.ts, src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetCalculator.ts, src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetDrawer.ts, src/MusicalScore/ScoreIO/MusicSymbolModules/ExpressionReader.ts, src/MusicalScore/VoiceData/Expressions/MultiExpression.ts, src/MusicalScore/VoiceData/Expressions/MultiTempoExpression.ts
added  missing implementation for uncategorized/unknown (no tempo or dynamic, ..) expressions to get rendered.
Please check the visuals - now there might be some expressions becoming visible..
=> Fix: added rendering uncategorized/unknown expressions

src/MusicalScore/Graphical/MusicSystemBuilder.ts, src/MusicalScore/ScoreIO/InstrumentReader.ts, src/MusicalScore/ScoreIO/MusicSymbolModules/RepetitionInstructionReader.ts
fixed breaking the system if the last measure has an endline (thin-bold line)
System stretching seems to not work still for these ending systems...
=> fix: fixed breaking the system if the last measure has an endline 

src/MusicalScore/Graphical/VexFlow/VexFlowConverter.ts, src/MusicalScore/ScoreIO/InstrumentReader.ts, src/MusicalScore/ScoreIO/MusicSymbolModules/ArticulationReader.ts, src/MusicalScore/ScoreIO/VoiceGenerator.ts, src/MusicalScore/VoiceData/TabNote.ts, src/MusicalScore/VoiceData/VoiceEntry.ts
git fetch and git pull created an error because feat/tabs existed beforehand, apparently, and feat/tabs/bend-release makes tabs a directory instead of a branch now.
-> deleate feat/tabs/bend-release, keep feat/tab/bend-release
=> fix branch name

src/MusicalScore/Graphical/VexFlow/VexFlowConverter.ts, src/MusicalScore/ScoreIO/InstrumentReader.ts, src/MusicalScore/ScoreIO/MusicSymbolModules/ArticulationReader.ts, src/MusicalScore/ScoreIO/VoiceGenerator.ts, src/MusicalScore/VoiceData/TabNote.ts, src/MusicalScore/VoiceData/VoiceEntry.ts, test/Util/generateImages_browserless.js
Merging #812 into develop.
adds bends and releases to tabs.
tested, no visual diffs.
sample will be added in next commit.
=> merge Feat/tab/bend-release to develop

demo/index.js, src/MusicalScore/Graphical/EngravingRules.ts, src/MusicalScore/ScoreIO/MusicSheetReader.ts, src/OpenSheetMusicDisplay/OSMDOptions.ts, src/OpenSheetMusicDisplay/OpenSheetMusicDisplay.ts
Implements https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/541
=> Add option to read measure numbers from musicxml measure attribute

src/MusicalScore/Graphical/SkyBottomLineCalculator.ts
First pass at fixing issue 911
=> initial fix

src/MusicalScore/Graphical/BoundingBox.ts, src/MusicalScore/Graphical/GraphicalMusicSheet.ts, src/MusicalScore/Graphical/GraphicalObject.ts, src/MusicalScore/Graphical/VexFlow/VexFlowConverter.ts, src/MusicalScore/Graphical/VexFlow/VexFlowGraphicalNote.ts, src/MusicalScore/Graphical/VexFlow/VexFlowMeasure.ts, src/MusicalScore/Interfaces/AClassHierarchyTrackable.ts, src/OpenSheetMusicDisplay/OpenSheetMusicDisplay.ts, test/Util/generateImages_browserless.js
see #966
`GetNearestGraphicalObject()` taken over from audio player.
=> Fix GraphicalNote bounding box position (#966)

src/OpenSheetMusicDisplay/Cursor.ts, src/OpenSheetMusicDisplay/OSMDOptions.ts, src/OpenSheetMusicDisplay/OpenSheetMusicDisplay.ts, test/Common/OSMD/OSMD_Test.ts
This feature allows to configure multiple cursors with OSMDOptions.
=> Feature: Multiple cursors

src/MusicalScore/ScoreIO/MusicSymbolModules/ExpressionReader.ts
Proposed fix for #1045, tested successfully on the sheet mentioned in the issue.
=> Fixes decimal tempo parsing and handling dotted beats

src/Common/DataObjects/Fraction.ts, src/MusicalScore/Graphical/GraphicalNote.ts, src/MusicalScore/Graphical/VexFlow/VexFlowConverter.ts, src/MusicalScore/Graphical/VexFlow/VexFlowMeasure.ts, src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetCalculator.ts, src/MusicalScore/Graphical/VexFlow/VexFlowTabMeasure.ts
See https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/1062#issuecomment-924419798 and further comments.
=> Fix Cross Stave Note Position X-Shift and Ghost Notes for complex fractions

src/OpenSheetMusicDisplay/OSMDOptions.ts
Fixed error in the docs (cursor follow/alpha descriptions were switched)
=> docs: docstring correction

src/MusicalScore/Graphical/VexFlow/VexFlowConverter.ts, src/MusicalScore/ScoreIO/InstrumentReader.ts, src/MusicalScore/ScoreIO/VoiceGenerator.ts, src/MusicalScore/VoiceData/Note.ts
=> Fix dots in tuplets

src/MusicalScore/Graphical/MusicSheetCalculator.ts, test/data/test_octave-shift_simple_piano.musicxml
Fix #1099
No visual diffs. See above for sample.
=> Fix octave shift display octave with multiple shifts in one measure

src/MusicalScore/Graphical/VexFlow/VexFlowMeasure.ts, src/MusicalScore/ScoreIO/InstrumentReader.ts, test/data/test_clefs_instaff_secondvoice_backup_forward.musicxml
=> Fix Clefs missing (in-staff, 2nd voice or with backup/forward tags)

src/OpenSheetMusicDisplay/Cursor.ts, src/OpenSheetMusicDisplay/OpenSheetMusicDisplay.ts
@sschmidTU testing with the migration I have realised that the independent control of follow for multiple cursors was not working.
Do you agree with the approach?
- the general one, if set, forces to follow all the cursors.
- the independent one, if set, forces to follow this particular cursor
=> Fix follow for multiple cursors

src/MusicalScore/Graphical/GraphicalMeasure.ts, src/MusicalScore/Graphical/MusicSheetCalculator.ts, src/MusicalScore/Graphical/MusicSystemBuilder.ts, src/MusicalScore/Instrument.ts
=> feat(Transposing): Able to transpose single instrument (#1115)

src/MusicalScore/ScoreIO/InstrumentReader.ts, test/data/test_clef_end_measure.musicxml
Fixes #1120 (in-staff clef missing).
No diffs in visual regression (prior to adding new sample that tests this).
=> Fix clefs missing (#1120)

README.md, package.json, src/MusicalScore/Graphical/EngravingRules.ts, src/MusicalScore/Graphical/MusicSheetCalculator.ts, src/MusicalScore/Graphical/VexFlow/VexFlowMeasure.ts, src/MusicalScore/ScoreIO/VoiceGenerator.ts, src/MusicalScore/VoiceData/ChordSymbolContainer.ts, src/MusicalScore/VoiceData/Staff.ts
Vexflow updated to release 4.0.1.
Merged changes from develop.
@sschmidTU @infojunkie it would be very nice to get your feedback for the next vexflow bug release 4.0.2 or next release 4.1.0
=> Feat/vexflow 4.0.1

package.json, src/MusicalScore/Graphical/VexFlow/VexFlowConverter.ts, src/MusicalScore/Graphical/VexFlow/VexFlowMeasure.ts
@sschmidTU this should fix some open issues, please have a look at the visual regression.
=> Vexflow 4.0.3

src/MusicalScore/Graphical/VexFlow/VexFlowMeasure.ts, src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetCalculator.ts, src/VexFlowPatch/src/formatter.js, test/data/test_12-8-rhythm-overflow.musicxml
=> Fix 12/8 layout overflowing into next measure

src/Util/CollectionUtil.ts
Fixes #1201
visual regression tests show no diffs.
sample: [bee.zip](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/files/9258905/bee.zip)
=> Fix rare infinite loop in CollectionUtil.binarySearch

src/MusicalScore/Graphical/VexFlow/VexFlowConverter.ts, src/VexFlowPatch/readme.txt, src/VexFlowPatch/src/stavenote.js, test/data/test_drums_slash_chord.musicxml
See #1228
No visual regressions after the latest commit.
=> Fix Slash notehead overwriting other noteheads in VoiceEntry

src/VexFlowPatch/src/renderer.js
=> Performance: CanvasContext: add willReadFrequently attribute (marginal improvement)

src/MusicalScore/ScoreIO/MusicSymbolModules/ExpressionReader.ts, src/MusicalScore/VoiceData/Expressions/ContinuousExpressions/ContinuousDynamicExpression.ts
fix #1259
visual regression tests show only one expected diff after latest commit:
duplicate wedge removed in Gretchaninov - A Boring Story
=> Fix wedge duplicates (e.g. crescendo)

src/MusicalScore/Graphical/EngravingRules.ts, src/MusicalScore/Graphical/VexFlow/VexFlowMeasure.ts, src/MusicalScore/ScoreIO/MusicSymbolModules/RepetitionInstructionReader.ts, src/VexFlowPatch/src/staverepetition.js
visual regression tests only show minimal changes after https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/pull/1265/commits/0ee4b84d738422cef6cc8abb32d91ce3bfcd47ef.
=> Fix repetition symbol / text too far left (e.g. D.C.)

src/MusicalScore/ScoreIO/MusicSymbolModules/SlurReader.ts, src/MusicalScore/VoiceData/Note.ts, test/data/test_slur_double.musicxml
=> Fix double slur with different placement ignored

src/MusicalScore/Graphical/VexFlow/VexFlowConverter.ts, src/MusicalScore/VoiceData/VoiceEntry.ts, test/data/test_fermata_inverted_placement.musicxml
fixes #1278
no visual regressions.
=> fix fermata inverted placement

src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetCalculator.ts, src/MusicalScore/Graphical/VexFlow/VexFlowPedal.ts, src/MusicalScore/VoiceData/Expressions/ContinuousExpressions/Pedal.ts, src/VexFlowPatch/src/pedalmarking.js
Fixes #1306
no diffs except for new sample `test_pedal_systembreak.musicxml`
=> Fix pedal starting at rest note start x-position

src/MusicalScore/Graphical/BoundingBox.ts, src/MusicalScore/Graphical/EngravingRules.ts, src/MusicalScore/Graphical/GraphicalGlissando.ts, src/MusicalScore/Graphical/MusicSheetCalculator.ts, src/MusicalScore/Graphical/StaffLine.ts, src/MusicalScore/Graphical/VexFlow/VexFlowGlissando.ts, src/MusicalScore/Graphical/VexFlow/VexFlowMeasure.ts, src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetCalculator.ts, src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetDrawer.ts, src/MusicalScore/Graphical/VexFlow/index.ts, src/MusicalScore/Graphical/index.ts, src/MusicalScore/ScoreIO/MusicSymbolModules/SlurReader.ts, src/MusicalScore/ScoreIO/VoiceGenerator.ts, src/MusicalScore/VoiceData/Glissando.ts, src/MusicalScore/VoiceData/Note.ts, src/MusicalScore/VoiceData/index.ts, src/VexFlowPatch/src/stavetie.js, src/VexFlowPatch/src/tabnote.js, test/data/test_gliss_simple_g_c.musicxml, test/data/test_slide_glissando.musicxml
=> feat: Glissando and Slide (WIP)

src/MusicalScore/Graphical/MusicSheetCalculator.ts
Keeping fingering position if it was set to a fixed value.
Adresses #1348
=> Better fingering position selection

src/MusicalScore/Graphical/EngravingRules.ts, src/MusicalScore/Graphical/MusicSheetCalculator.ts, src/OpenSheetMusicDisplay/OSMDOptions.ts, src/OpenSheetMusicDisplay/OpenSheetMusicDisplay.ts
Modified
EngravingRules.AutoGenerate**Mutiple**RestMeasuresFromRestMeasures
to
EngravingRules.AutoGenerate**Multiple**RestMeasuresFromRestMeasures.
Modified
IOSMDOptions.autoGenerate**Mutiple**RestMeasuresFromRestMeasures
to
IOSMDOptions.autoGenerate**Multiple**RestMeasuresFromRestMeasures.
=> Small Improvements in Code Clarity

src/MusicalScore/Graphical/EngravingRules.ts, src/MusicalScore/Graphical/GraphicalLyricEntry.ts, src/MusicalScore/Graphical/VexFlow/VexFlowConverter.ts, src/MusicalScore/Graphical/VexFlow/VexFlowVoiceEntry.ts, src/VexFlowPatch/readme.txt, src/VexFlowPatch/src/stavenote.js, test/data/test_lyrics_spacing_short_notes_four_characters.musicxml
closes #1394
running visual regression tests now
=> Lyrics Spacing: Add x-padding for short notes with long lyrics

src/MusicalScore/Graphical/GraphicalMeasure.ts, src/MusicalScore/Graphical/MusicSystemBuilder.ts, src/MusicalScore/Graphical/VexFlow/VexFlowMeasure.ts, test/data/test_key_signature_accidental.musicxml, test/data/test_key_signature_accidental_clefchange.musicxml, test/data/test_key_signature_accidental_stress_test_multiple_instruments_changes.musicxml
Fixes #1423
before:
after:
(yes, it's a little... unfortunate that we didn't catch this before ;) )
before:
after:
=> Fix key signatures accidentals wrong for key changes in certain clefs

src/MusicalScore/Graphical/EngravingRules.ts, src/MusicalScore/Graphical/MusicSheetCalculator.ts, src/MusicalScore/ScoreIO/MusicSheetReader.ts, src/MusicalScore/VoiceData/SourceMeasure.ts, test/data/test_chord_whole_rest_double_chord.musicxml, test/data/test_chord_whole_rest_overlap.musicxml
Fixes #1445, #599, #791
Also related to #1443
after:
before:
=> Fix Chord Symbols not over a note not displayed

src/VexFlowPatch/src/bend.js
=> Fix Tab bend moving on second render (re-render)

src/MusicalScore/Graphical/EngravingRules.ts, src/MusicalScore/Graphical/GraphicalLabel.ts, src/MusicalScore/Graphical/MusicSheetCalculator.ts, src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetDrawer.ts, src/MusicalScore/ScoreIO/MusicSymbolModules/ExpressionReader.ts, src/MusicalScore/VoiceData/Expressions/AbstractExpression.ts, test/data/test_direction_color.musicxml
=> feat(Color): Words nodes / expressions use XML color by default.
